global:
  host: index-egapro.travail.gouv.fr

simulateur:
  host: index-egapro.travail.gouv.fr
  redirectFrom:
    - "{{ .Values.global.host }}"

  
api:
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: smtp